"rmc install" understands "--prefix=DIRECTORY"

diff --git a/scripts/rmc-commands/install b/scripts/rmc-commands/install
--- a/scripts/rmc-commands/install
+++ b/scripts/rmc-commands/install
@@ -22,11 +22,18 @@ show_help_and_exit() {
     echo "             of ROSE that doesn't pass and should only be used for development,"
     echo "             not actual releases intended for users."
     echo
+    echo "         --prefix=DIRECTORY"
+    echo "             Directory into which ROSE should be installed. For cmake and GNU"
+    echo "             Autotools builds, if a directory is specified here it must match"
+    echo "             the intallation prefix directory that was specified during the"
+    echo "             configuration step; tup is able to retarget the installation to"
+    echo "             any directory during the install step."
     exit 0
 }
 
 run_tests=yes
 dry_run=
+prefix=
 while [ "$#" -gt 0 ]; do
     case "$1" in
 	--) shift; break ;;
@@ -34,6 +41,7 @@ while [ "$#" -gt 0 ]; do
 	-n|--dry-run) dry_run=--dry-run; shift ;;
 	--tests) run_tests=yes; shift ;;
 	--no-tests) run_tests=; shift ;;
+	--prefix=*) prefix="${1#--prefix=}"; shift ;;
 	-*) die "unknown command-line switch \"$1\"" ;;
 	*) die "incorrect usage; see --help" ;;
     esac
@@ -41,25 +49,49 @@ done
 
 case "$RMC_BUILD" in
     autoconf)
+	if [ -n "$prefix" ]; then
+	    old_prefix="$(sed -n 's/^prefix[ \t]*=[ \t]*//p' "$RG_BLD/Makefile")"
+	    if [ "$old_prefix" != "$prefix" ]; then
+		echo "$arg0: error: you cannot change the installation prefix for GNU Autotools builds" >&2
+		echo "$arg0: info: originally specified prefix was \"$old_prefix\"" >&2
+		echo "$arg0: info: newly specified prefix is \"$prefix\"" >&2
+		exit 1
+	    fi
+	fi
+	
 	"$dir0/make" -C "$RG_BLD/src" $dry_run
 	[ -n "$run_tests" ] && "$dir0/make" -C "$RG_BLD" $dry_run check
 	"$dir0/make" -C "$RG_BLD" $dry_run install-rose-library
 	;;
+
     cmake)
+	if [ -n "$prefix" ]; then
+	    old_prefix="$(sed -n 's/^CMAKE_INSTALL_PREFIX:.*=//p' "$RG_BLD/CMakeCache.txt")"
+	    if [ "$old_prefix" != "$prefix" ]; then
+		echo "$arg0: error: you canot change the installation prefix for CMake builds" >&2
+		echo "$arg0: info: originally specified prefix was \"$old_prefix\"" >&2
+		echo "$arg0: info: newly specified prefix is \"$prefix\"" >&2
+		exit 1
+	    fi
+	fi
+	
 	"$dir0/make" -C "$RG_BLD/src" $dry_run
 	[ -n "$run_tests" ] && die "I don't know how to run ROSE tests with CMake"
 	"$dir0/make" -C "$RG_BLD" install
 	;;
+
     tup)
 	# Tup install automatically runs tests
 	if [ -n "$run_tests" ]; then
-	    "$dir0/make" -C "$RG_BLD" install
+	    env RMC_INSTALLED=$prefix "$dir0/make" -C "$RG_BLD" install
 	else
 	    "$dir0/make" -C "$RG_BLD/src"
 	    (
 		set -x
 		cd "$RG_BLD"
-		$RG_SRC/scripts/tup/install-staged --next --build-type=untested --exclude='projects/MatrixTestingProject/*'
+		$RG_SRC/scripts/tup/install-staged --next --build-type=untested \
+						   --exclude='projects/MatrixTestingProject/*' \
+						   $prefix
 	    )
 	fi
 	;;
